#!/usr/bin/env bash
set -euo pipefail

# Library-only scanner implementation. Authority resolution must happen before
# either function is called. This file is intentionally not an executable
# free-form target surface.
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  echo "scanner-core.sh is library-only; resolve an authorized target before sourcing it." >&2
  exit 2
fi

WQT_SCANNER_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

wqt_report_dir_for_output() {
  if [[ "$#" -ne 1 || -z "$1" ]]; then
    echo "wqt_report_dir_for_output requires: <raw-output-path>" >&2
    return 2
  fi

  local output_dir
  output_dir="$(dirname "$1")"
  if [[ "$(basename "$output_dir")" == "raw" ]]; then
    printf '%s/reports\n' "$(dirname "$output_dir")"
  else
    printf '%s/reports\n' "$output_dir"
  fi
}

wqt_run_siteone() {
  if [[ "$#" -ne 2 ]]; then
    echo "wqt_run_siteone requires: <validated-origin> <output-path>" >&2
    return 2
  fi

  local target="$1"
  local output="$2"
  local binary="${SITEONE_BIN:-${WQT_SCANNER_ROOT_DIR}/tools/bin/siteone-crawler}"
  local report_dir
  local siteone_report

  if [[ -z "$target" || -z "$output" ]]; then
    echo "wqt_run_siteone requires non-empty validated origin and output path" >&2
    return 2
  fi
  if [[ ! -x "$binary" ]]; then
    echo "SiteOne binary not found or not executable: ${binary}" >&2
    return 1
  fi

  report_dir="$(wqt_report_dir_for_output "$output")"
  siteone_report="${report_dir}/siteone.html"
  mkdir -p "$(dirname "$output")" "$report_dir"
  rm -f "$output" "$siteone_report"

  # Evidence-establishing run: intentionally NO --ci, --browser, --ai-*, --upload,
  # or mail path. The source-native HTML is presentation/debug evidence only; it
  # is generated by the same crawl that produces the canonical raw JSON input.
  "$binary" \
    --url="$target" \
    --output=json \
    --output-json-file="$output" \
    --output-html-report="$siteone_report" \
    --output-text-file='' \
    --http-cache-dir='' \
    --workers=2 \
    --max-reqs-per-sec=5 \
    --hide-progress-bar \
    --no-color

  test -s "$output"
  test -s "$siteone_report"
}

wqt_run_lighthouse() {
  if [[ "$#" -ne 2 ]]; then
    echo "wqt_run_lighthouse requires: <validated-origin> <output-path>" >&2
    return 2
  fi

  local target="$1"
  local output="$2"
  local lighthouse_bin="${WQT_SCANNER_ROOT_DIR}/node_modules/.bin/lighthouse"
  local chrome_path="${CHROME_PATH:-}"
  local report_dir
  local report_base
  local generated_json
  local generated_html
  local lighthouse_report

  if [[ -z "$target" || -z "$output" ]]; then
    echo "wqt_run_lighthouse requires non-empty validated origin and output path" >&2
    return 2
  fi
  if [[ ! -x "$lighthouse_bin" ]]; then
    echo "Lighthouse CLI not installed at ${lighthouse_bin}" >&2
    return 1
  fi

  if [[ -z "$chrome_path" ]]; then
    local candidate
    for candidate in google-chrome google-chrome-stable chromium chromium-browser; do
      if command -v "$candidate" >/dev/null 2>&1; then
        chrome_path="$(command -v "$candidate")"
        break
      fi
    done
  fi
  if [[ -z "$chrome_path" || ! -x "$chrome_path" ]]; then
    echo "No supported Chrome/Chromium executable found for Lighthouse" >&2
    return 1
  fi

  report_dir="$(wqt_report_dir_for_output "$output")"
  report_base="${report_dir}/lighthouse"
  generated_json="${report_base}.report.json"
  generated_html="${report_base}.report.html"
  lighthouse_report="${report_dir}/lighthouse.html"
  mkdir -p "$(dirname "$output")" "$report_dir"
  rm -f "$output" "$generated_json" "$generated_html" "$lighthouse_report"

  "$chrome_path" --version
  # Lighthouse supports multiple reporters in one execution. JSON remains the
  # raw machine evidence; HTML is source-native operator/debug presentation.
  CHROME_PATH="$chrome_path" "$lighthouse_bin" "$target" \
    --preset=desktop \
    --only-categories=performance,accessibility,best-practices,seo \
    --output=json \
    --output=html \
    --output-path="$report_base" \
    --quiet \
    --chrome-flags="--headless=new --no-sandbox --disable-dev-shm-usage --disable-gpu"

  test -s "$generated_json"
  test -s "$generated_html"
  mv "$generated_json" "$output"
  mv "$generated_html" "$lighthouse_report"
  test -s "$output"
  test -s "$lighthouse_report"
}
